import path from 'path';
import { NextResponse } from 'next/server';
import { put } from '@vercel/blob';
import { generateImage, generateText, JSONValue } from 'ai';

import { ChatMessage } from '@/types';
import { env } from '@/lib/env';
import { getImageModel, getLanguageModel } from '@/lib/provider';
import { findModelByModelId, getTitleSettings } from '@/lib/queries';
import { generateUUID } from '@/lib/utils';
import { auth } from '@/server/auth';
import { api } from '@/trpc/server';

export const maxDuration = 60;

type PostData = {
  id: string;
  modelId: string;
  userMessage: Omit<ChatMessage, 'role'> & { role: 'user' };
  parentMessageId?: string;
  n?: number;
  size?: `${number}x${number}`;
  aspectRatio?: `${number}:${number}`;
  seed?: number;
  providerOptions?: Record<string, Record<string, JSONValue>>;
};

export async function POST(req: Request) {
  const session = await auth();

  if (!session?.user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const json: PostData = await req.json();
  const id = json.id || generateUUID();
  const {
    modelId,
    userMessage,
    parentMessageId,
    n = 1,
    size,
    aspectRatio = '16:9',
    seed,
    providerOptions
  } = json;

  if (!modelId || !userMessage) {
    return NextResponse.json(
      { error: 'Invalid modelId and userMessage parameters' },
      { status: 400 }
    );
  }

  // Fetch model from database to validate
  const dbModel = await findModelByModelId(modelId, 'image');
  if (!dbModel?.provider) {
    return NextResponse.json(
      { error: `Model ${modelId} is not available` },
      { status: 403 }
    );
  }

  let title = 'Untitled';
  const chat = await api.chat.detail({
    id,
    type: 'image',
    includeMessages: false
  });
  if (!chat) {
    try {
      const {
        prompt: titlePrompt,
        modelId: titleModelId,
        provider: titleProvider
      } = await getTitleSettings();

      // Only generate title if all settings are configured
      if (titlePrompt && titleModelId && titleProvider) {
        const { text } = await generateText({
          model: getLanguageModel(titleProvider, titleModelId),
          system: titlePrompt,
          prompt: JSON.stringify(userMessage)
        });

        title = text ?? title;
      }
    } catch (err: any) {
      console.error(`Generate title error:`, err.message);
    }

    await api.chat.create({
      id,
      title,
      type: 'image',
      modelId,
      messages: [userMessage]
    });
  } else {
    title = chat.title;
    // Update modelId if it has changed
    if (chat.modelId !== modelId) {
      await api.chat.update({ id, modelId });
    }
    if (parentMessageId && parentMessageId === userMessage.id) {
      await api.message.delete({ parentId: parentMessageId });
    } else {
      await api.message.create({
        chatId: id,
        messages: [userMessage]
      });
    }
  }

  try {
    const textParts = userMessage.parts
      ?.filter(part => part.type === 'text')
      .map(part => part.text)
      .join('\n')
      .trim();

    let imageBase64: string;
    let imageMediaType: string;

    const isGeminiImageModel =
      modelId.startsWith('gemini-2.5-flash-image') ||
      modelId.startsWith('gemini-3-pro-image');

    if (isGeminiImageModel) {
      // Gemini models generate images via generateText with multi-modal output
      const mergedProviderOptions = {
        ...(dbModel.provider.apiOptions && {
          [dbModel.provider.type]: dbModel.provider.apiOptions
        }),
        ...providerOptions
      } as any;
      const result = await generateText({
        model: getLanguageModel(dbModel.provider, modelId),
        prompt: textParts,
        temperature: dbModel.apiParams?.temperature,
        topP: dbModel.apiParams?.topP,
        topK: dbModel.apiParams?.topK,
        maxOutputTokens: dbModel.apiParams?.maxOutputTokens,
        frequencyPenalty: dbModel.apiParams?.frequencyPenalty,
        presencePenalty: dbModel.apiParams?.presencePenalty,
        providerOptions: mergedProviderOptions
      });

      const imageFile = result.files?.find(f =>
        f.mediaType.startsWith('image/')
      );
      if (!imageFile) {
        throw new Error('No image generated by the model');
      }

      imageBase64 = imageFile.base64;
      imageMediaType = imageFile.mediaType;
    } else {
      // Standard image models use generateImage API
      const { image } = await generateImage({
        model: getImageModel(dbModel.provider, modelId),
        prompt: textParts,
        n,
        size,
        aspectRatio,
        seed,
        providerOptions: {
          ...(dbModel.provider.apiOptions && {
            [dbModel.provider.type]: dbModel.provider.apiOptions
          }),
          ...providerOptions
        } as any
      });

      imageBase64 = image.base64;
      imageMediaType = image.mediaType;
    }

    const buffer = Buffer.from(imageBase64, 'base64');
    const ext = imageMediaType?.split('/')[1] || 'png';
    const filename = `${generateUUID()}.${ext}`;

    const pathname = path.join(
      env.UPLOAD_PATH,
      'generate-images',
      session.user.id,
      filename
    );
    const data = await put(pathname, buffer, {
      access: 'public',
      contentType: imageMediaType,
      addRandomSuffix: false
    });

    const assistantNow = new Date();
    const assistantMessage: ChatMessage = {
      id: generateUUID(),
      role: 'assistant',
      parts: [
        {
          type: 'file',
          mediaType: data.contentType || imageMediaType,
          url: data.url,
          filename
        }
      ],
      metadata: {
        parentId: userMessage.id,
        createdAt: assistantNow,
        updatedAt: assistantNow
      }
    };

    await api.message.create({
      chatId: id,
      messages: [assistantMessage]
    });

    return NextResponse.json({
      id,
      title,
      type: 'image',
      modelId,
      assistantMessage
    });
  } catch (err) {
    console.error('Image generation error:', err);
    return NextResponse.json(
      { error: 'Oops, an error occurred!' },
      { status: 500 }
    );
  }
}
